import transitivity from '@/assets/transitivity.jpg';
import mood from '@/assets/mood.jpg';
import theme from '@/assets/theme.jpg';

export const systems = [
  { id: 'transitivity', name: 'Transitivity', subtitle: 'Language as experience', metafunction: 'Ideational metafunction', image: transitivity, number: '01', description: 'Uncover the world within a clause. Explore processes, participants, and circumstances to understand how language represents experience.', tags: ['Processes', 'Participants', 'Circumstances'], labels: ['Material Process', 'Mental Process', 'Relational Process', 'Verbal Process', 'Behavioral Process', 'Existential Process', 'Actor', 'Goal', 'Senser', 'Phenomenon', 'Carrier', 'Attribute', 'Sayer', 'Verbiage', 'Existent', 'Circumstance: Location', 'Circumstance: Manner', 'Circumstance: Cause'], sample: 'The students explored the library yesterday.', annotations: [{ text: 'The students', label: 'Actor' }, { text: 'explored', label: 'Material Process' }, { text: 'the library', label: 'Goal' }, { text: 'yesterday', label: 'Circumstance: Location' }] },
  { id: 'mood', name: 'Mood', subtitle: 'Language as interaction', metafunction: 'Interpersonal metafunction', image: mood, number: '02', description: 'Discover the conversation behind a clause. Examine subjects, finite elements, and the choices that shape our relationships through language.', tags: ['Subject & Finite', 'Mood & Residue', 'Clause types'], labels: ['Subject', 'Finite', 'Predicator', 'Complement', 'Adjunct', 'Finite / Predicator', 'Declarative', 'Interrogative', 'Imperative'], sample: 'Will you explore the library?', annotations: [{ text: 'Will', label: 'Finite' }, { text: 'you', label: 'Subject' }, { text: 'explore', label: 'Predicator' }, { text: 'the library', label: 'Complement' }] },
  { id: 'theme', name: 'Theme', subtitle: 'Language as a message', metafunction: 'Textual metafunction', image: theme, number: '03', description: 'Follow the flow of meaning. Identify the starting point of a clause and discover how Theme and Rheme organize a message.', tags: ['Theme & Rheme', 'Topical Theme', 'Thematic structure'], labels: ['Textual Theme', 'Interpersonal Theme', 'Topical Theme', 'Rheme'], sample: 'However, the students explored the library.', annotations: [{ text: 'However,', label: 'Textual Theme' }, { text: 'the students', label: 'Topical Theme' }, { text: 'explored the library.', label: 'Rheme' }] },
] as const;
export type System = (typeof systems)[number];